module.exports = {
  // draft
  SYNC_DRAFTS: 'SYNC_DRAFTS',

  // tab
  TAB_SELECTED: 'TAB_SELECTED',

  // user
  USER_INFO: 'USER_INFO',
  CURRENT_BOARD_USER_INFO: 'CURRENT_BOARD_USER_INFO',

  // home
  USER_MESSAGE_LOADING: 'USER_MESSAGE_LOADING',
  USER_MESSAGE_GET: 'USER_MESSAGE_GET',
  USER_MESSAGE_APPEND: 'USER_MESSAGE_APPEND',
  USER_MESSAGE_COUNT: 'USER_MESSAGE_COUNT',

  // board
  BOARD_BANNER: 'BOARD_BANNER',
  BOARD_LIST_GET: 'BOARD_LIST_GET',
  BOARD_LIST_LOADING: 'BOARD_LIST_LOADING',
  BOARD_SELECTED: 'BOARD_SELECTED',
  BOARD_EXIT: 'BOARD_EXIT',
  BOARD_CURRENT: 'BOARD_CURRENT',
  BOARD_FEED: 'BOARD_FEED',
  BOARD_CURRENT_LOADING: 'BOARD_CURRENT_LOADING',
  BOARD_UPDATE: 'BOARD_UPDATE',
  BOARD_ALL_TAGS: 'BOARD_ALL_TAGS',
  BOARD_ALL_CATEGORY: 'BOARD_ALL_CATEGORY',
  BOARD_FILE_LIST_LOADING: 'BOARD_FILE_LIST_LOADING',
  BOARD_FILE_LIST_GET: 'BOARD_FILE_LIST_GET',
  BOARD_FILE_LIST_APPEND: 'BOARD_FILE_LIST_APPEND',

  // board create
  BOARD_CREATE_CLEAR: 'BOARD_CREATE_CLEAR',
  BOARD_CREATE_EDIT_ATTRIBUTE: 'BOARD_CREATE_EDIT_ATTRIBUTE',

  // today sign
  TODAY_SIGN_LIST_LOADING: 'TODAY_SIGN_LIST_LOADING',
  TODAY_SIGN_LIST_GET: 'TODAY_SIGN_LIST_GET',
  TODAY_SIGN_LIST_APPEND: 'TODAY_SIGN_LIST_APPEND',
  TODAY_SIGN_REMOVE: 'TODAY_SIGN_REMOVE',
  TODAY_SIGN_LIKE: 'TODAY_SIGN_LIKE',
  TODAY_SIGN_COMMENT_CREATE: 'TODAY_SIGN_COMMENT_CREATE',
  TODAY_SIGN_COMMENT_REMOVE: 'TODAY_SIGN_COMMENT_REMOVE',

  // SIGN
  SIGN_LIST_LOADING: 'SIGN_LIST_LOADING',
  SIGN_LIST_GET: 'SIGN_LIST_GET',
  SIGN_LIST_APPEND: 'SIGN_LIST_APPEND',
  SIGN_REMOVE: 'SIGN_REMOVE',
  SIGN_LIKE: 'SIGN_LIKE',
  SIGN_COMMENT_CREATE: 'SIGN_COMMENT_CREATE',
  SIGN_COMMENT_REMOVE: 'SIGN_COMMENT_REMOVE',

  // topic
  TOPIC_LIST_LOADING: 'TOPIC_LIST_LOADING',
  TOPIC_LIST_GET: 'TOPIC_LIST_GET',
  TOPIC_LIST_APPEND: 'TOPIC_LIST_APPEND',
  TOPIC_STICK_LIST: 'TOPIC_STICK_LIST',
  TOPIC_LIST_LIKE: 'TOPIC_LIST_LIKE',
  TOPIC_DELETE: 'TOPIC_DELETE',
  TOPIC_STICK: 'TOPIC_STICK',
  TOPIC_SET_ESSENTIAL: 'TOPIC_SET_ESSENTIAL',
  TOPIC_ADD_SHARE_COUNT: 'TOPIC_ADD_SHARE_COUNT',

  // topic edit
  TOPIC_EDIT_INIT: 'TOPIC_EDIT_INIT',
  TOPIC_EDIT_CLEAR: 'TOPIC_EDIT_CLEAR',
  TOPIC_EDIT_ADD_MEDIA_IMAGE: 'TOPIC_EDIT_ADD_MEDIA_IMAGE',
  TOPIC_EDIT_ADD_MEDIA_VIDEO: 'TOPIC_EDIT_ADD_MEDIA_VIDEO',
  TOPIC_EDIT_ADD_FILES: 'TOPIC_EDIT_ADD_FILES',
  TOPIC_EDIT_DELETE_MEDIA: 'TOPIC_EDIT_DELETE_MEDIA',
  TOPIC_EDIT_DELETE_FILE: 'TOPIC_EDIT_DELETE_FILE',
  TOPIC_EDIT_DRAG_MEDIA: 'TOPIC_EDIT_DRAG_MEDIA',
  TOPIC_EDIT_UPDATE_MEDIA_IMAGE: 'TOPIC_EDIT_UPDATE_MEDIA_IMAGE',
  TOPIC_EDIT_EDIT_ATTRIBUTE: 'TOPIC_EDIT_EDIT_ATTRIBUTE',
  TOPIC_EDIT_ADD_KEY_FOR_MEDIA: 'TOPIC_EDIT_ADD_KEY_FOR_MEDIA',
  TOPIC_EDIT_ADD_KEY_FOR_FILE: 'TOPIC_EDIT_ADD_KEY_FOR_FILE',

  // question
  QUESTION_LIST_LOADING: 'QUESTION_LIST_LOADING',
  QUESTION_LIST_GET: 'QUESTION_LIST_GET',
  QUESTION_LIST_APPEND: 'QUESTION_LIST_APPEND',
  QUESTION_ANSWER_LIKE: 'QUESTION_ANSWER_LIKE',
  QUESTION_REMOVE: 'QUESTION_REMOVE',
  QUESTION_ANSWER_REMOVE: 'QUESTION_ANSWER_REMOVE',
  QUESTION_LIST_UPDATE_ROW: 'QUESTION_LIST_UPDATE_ROW',

  // my question
  MY_QUESTION_LIST_LOADING: 'MY_QUESTION_LIST_LOADING',
  MY_QUESTION_LIST_GET: 'MY_QUESTION_LIST_GET',
  MY_QUESTION_LIST_APPEND: 'MY_QUESTION_LIST_APPEND',
  MY_QUESTION_ANSWER_LIKE: 'MY_QUESTION_ANSWER_LIKE',
  MY_QUESTION_REMOVE: 'MY_QUESTION_REMOVE',
  MY_QUESTION_ANSWER_REMOVE: 'MY_QUESTION_ANSWER_REMOVE',
  MY_QUESTION_LIST_UPDATE_ROW: 'MY_QUESTION_LIST_UPDATE_ROW',

  MY_EVENT_ENROLL_LIST_LOADING: 'MY_EVENT_ENROLL_LIST_LOADING',
  MY_EVENT_ENROLL_LIST_GET: 'MY_EVENT_ENROLL_LIST_GET',
  MY_EVENT_ENROLL_LIST_APPEND: 'MY_EVENT_ENROLL_LIST_APPEND',
  MY_EVENT_ENROLL_REMOVE: 'MY_EVENT_ENROLL_REMOVE',

  // event edit
  EVENT_EDIT_INIT: 'EVENT_EDIT_INIT',
  EVENT_EDIT_CLEAR: 'EVENT_EDIT_CLEAR',
  EVENT_EDIT_EDIT_ATTRIBUTE: 'EVENT_EDIT_EDIT_ATTRIBUTE',

  // event
  EVENT_LIST_LOADING: 'EVENT_LIST_LOADING',
  EVENT_LIST_GET: 'EVENT_LIST_GET',
  EVENT_LIST_APPEND: 'EVENT_LIST_APPEND',
  EVENT_REMOVE: 'EVENT_REMOVE',
  EVENT_ALL_TYPES: 'EVENT_ALL_TYPES',
  EVENT_ALL_CATEGORY: 'EVENT_ALL_CATEGORY',

  // message
  MESSAGE_COUNT: 'MESSAGE_COUNT',
  MESSAGE_LIST_CLEAR: 'MESSAGE_LIST_CLEAR',
  MESSAGE_LIST_LOADING: 'MESSAGE_LIST_LOADING',
  MESSAGE_LIST_GET: 'MESSAGE_LIST_GET',
  MESSAGE_LIST_APPEND: 'MESSAGE_LIST_APPEND',
  MESSAGE_COMMENT_LIKE: 'MESSAGE_COMMENT_LIKE',
  MESSAGE_COMMENT_REMOVE: 'MESSAGE_COMMENT_REMOVE',
  MESSAGE_USER_FOLLOW: 'MESSAGE_USER_FOLLOW',

  // follow feed
  FOLLOW_FEED_LOADING: 'FOLLOW_FEED_LOADING',
  FOLLOW_FEED_GET: 'FOLLOW_FEED_GET',
  FOLLOW_FEED_APPEND: 'FOLLOW_FEED_APPEND',

  // essential
  ESSENTIAL_LIST_LOADING: 'ESSENTIAL_LIST_LOADING',
  ESSENTIAL_LIST_GET: 'ESSENTIAL_LIST_GET',
  ESSENTIAL_LIST_APPEND: 'ESSENTIAL_LIST_APPEND',
  ESSENTIAL_LIST_LIKE: 'ESSENTIAL_LIST_LIKE',
  ESSENTIAL_DELETE: 'ESSENTIAL_DELETE',
  ESSENTIAL_STICK: 'ESSENTIAL_STICK',
  ESSENTIAL_SET_ESSENTIAL: 'ESSENTIAL_SET_ESSENTIAL',

  // utils
  UTIL_VERIFY_COUNTDOWN: 'UTIL_VERIFY_COUNTDOWN',
  AUDIO_PLAYING_URL: 'AUDIO_PLAYING_URL',
  AUDIO_PLAYING: 'AUDIO_PLAYING',

  // manage
  MANAGE_TOPIC_LIST_LOADING: 'MANAGE_TOPIC_LIST_LOADING',
  MANAGE_TOPIC_LIST_GET: 'MANAGE_TOPIC_LIST_GET',
  MANAGE_TOPIC_LIST_APPEND: 'MANAGE_TOPIC_LIST_APPEND',
  MANAGE_TOPIC_DELETE: 'MANAGE_TOPIC_DELETE',
  MANAGE_TOPIC_STICK: 'MANAGE_TOPIC_STICK',
  MANAGE_TOPIC_SET_ESSENTIAL: 'MANAGE_TOPIC_SET_ESSENTIAL',
  MANAGE_MEMBER_LIST_LOADING: 'MANAGE_MEMBER_LIST_LOADING',
  MANAGE_MEMBER_LIST_GET: 'MANAGE_MEMBER_LIST_GET',
  MANAGE_MEMBER_LIST_APPEND: 'MANAGE_MEMBER_LIST_APPEND',
  MANAGE_BLOCK_MEMBER_LIST_LOADING: 'MANAGE_BLOCK_MEMBER_LIST_LOADING',
  MANAGE_BLOCK_MEMBER_LIST_GET: 'MANAGE_BLOCK_MEMBER_LIST_GET',
  MANAGE_BLOCK_MEMBER_LIST_APPEND: 'MANAGE_BLOCK_MEMBER_LIST_APPEND',
  MANAGE_REVIEW_MEMBER_LIST_LOADING: 'MANAGE_REVIEW_MEMBER_LIST_LOADING',
  MANAGE_REVIEW_MEMBER_LIST_GET: 'MANAGE_REVIEW_MEMBER_LIST_GET',
  MANAGE_REVIEW_MEMBER_LIST_APPEND: 'MANAGE_REVIEW_MEMBER_LIST_APPEND',
  MANAGE_BLOCK_MEMBER: 'MANAGE_BLOCK_MEMBER',
  MANAGE_MEMBER_UPDATE: 'MANAGE_MEMBER_UPDATE',
  MANAGE_REVIEW_MEMBER: 'MANAGE_REVIEW_MEMBER',
  MANAGE_SIGN_LIST_LOADING: 'MANAGE_SIGN_LIST_LOADING',
  MANAGE_SIGN_LIST_GET: 'MANAGE_SIGN_LIST_GET',
  MANAGE_SIGN_LIST_APPEND: 'MANAGE_SIGN_LIST_APPEND',
  MANAGE_SIGN_REMOVE: 'MANAGE_SIGN_REMOVE',
  MANAGE_EVENT_LIST_LOADING: 'MANAGE_EVENT_LIST_LOADING',
  MANAGE_EVENT_LIST_GET: 'MANAGE_EVENT_LIST_GET',
  MANAGE_EVENT_LIST_APPEND: 'MANAGE_EVENT_LIST_APPEND',
  MANAGE_EVENT_REMOVE: 'MANAGE_EVENT_REMOVE',
  MANAGE_QUESTION_LIST_LOADING: 'MANAGE_QUESTION_LIST_LOADING',
  MANAGE_QUESTION_LIST_GET: 'MANAGE_QUESTION_LIST_GET',
  MANAGE_QUESTION_LIST_APPEND: 'MANAGE_QUESTION_LIST_APPEND',
  MANAGE_QUESTION_REMOVE: 'MANAGE_QUESTION_REMOVE',

  // article
  ARTICLE_LIST_GET: 'ARTICLE_LIST_GET',
  ARTICLE_LIST_APPEND: 'ARTICLE_LIST_APPEND',
  ARTICLE_LIST_LOADING: 'ARTICLE_LIST_LOADING',
  ARTICLE_REMOVE: 'ARTICLE_REMOVE',
}
